name = "cf-workers-status-page"
workers_dev = false
route = "status.mydot.app"
account_id = "585feca7df01ec32254a2b422252cdb1"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"



zone_id = "1b2d64cd41fc3cb07e6b2f76fb7a7e38"